Feat/day3
Trawais/2021_advent-of-code_PHP pull request #14
Opened 2022-03-04 09:41 UTC by daveingDave

2022-03-18 08:10 UTC, Trawais requested changes

2022-03-18 08:10 UTC, Trawais commented on src/day02/SubmarinePosition.php
> +<?php declare(strict_types=1);
The whole folder `day02` should not be in this pull-request.

2022-03-18 08:10 UTC, Trawais commented on src/day03/BitRates.php
> +        $gama = "";
`gama` and `epsilon` is forgotten here from the first part of the task. Should be removed.

2022-03-18 08:10 UTC, Trawais commented on src/day03/day03Test.php
> +        ];
I would not keep the ending box bracket on the new line but on the same.

2022-03-18 08:10 UTC, Trawais commented on src/day03/BitRates.php
> +        while(count($co2Rating)>1) {
Let's try to separate the same logic into only one function. One additional parameter must be added to decide whether you want to count ones or zeros.

2022-03-18 08:10 UTC, Trawais commented on src/day03/BitRates.php
> +        while(count($co2Rating)>1) {
Then I believe this code could be much shorther.

2022-03-22 13:21 UTC, Trawais approved these changes

2022-03-22 13:22 UTC, Trawais approved these changes

2022-03-22 13:22 UTC, Trawais commented on src/day03/BitRates.php
> +        return $this->getOxygenGeneratorOrCo2Rating($input ,1) * $this->getOxygenGeneratorOrCo2Rating($input, 0);
fix your code style (comma before `1`)

2022-03-31 15:19 UTC, Bollmanmkvb approved these changes

2022-04-12 07:50 UTC, merged